# Generated by Django 5.0.2 on 2025-12-03 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_desit_api', '0003_alumnos_maestros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nrc', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('seccion', models.CharField(blank=True, max_length=255, null=True)),
                ('dias', models.TextField(blank=True, null=True)),
                ('hora_inicio', models.CharField(blank=True, max_length=50, null=True)),
                ('hora_final', models.CharField(blank=True, max_length=50, null=True)),
                ('salon', models.CharField(blank=True, max_length=255, null=True)),
                ('programa', models.CharField(blank=True, max_length=255, null=True)),
                ('creditos', models.IntegerField(blank=True, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_escolar_desit_api.maestros')),
            ],
        ),
    ]
